---
- name: Node | restart kubelet
  command: /bin/true
  notify:
    - Kubelet | reload systemd
    - Kubelet | stop docker when migrated
    - Kubelet | restart kubelet

- name: Kubelet | reload systemd
  systemd:
    daemon_reload: true

- name: Kubelet | stop docker when migrated
  service:
    name: docker
    state: stopped
    enabled: false
  when:
    - force_stop_docker_demon

- name: Kubelet | restart kubelet
  service:
    name: kubelet
    state: restarted
