---
- name: Configure defaults
  debug:
    msg: "Check roles/kubespray-defaults/defaults/main.yml"
  tags:
    - always

- name: set fallback_ips
  include_tasks: fallback_ips.yml
  when:
    - fallback_ips is not defined

- name: set no_proxy
  include_tasks: no_proxy.yml
  when:
    - http_proxy is defined or https_proxy is defined
    - no_proxy is not defined
