---
- name: Migrate from docker | Ensure kubelet wants docker
  lineinfile:
    path: "/etc/systemd/system/kubelet.service"
    line: "After=docker.service"
    state: present
  check_mode: true
  register: kubelet_systemd_unit_need_docker

- name: Migrate from docker | Set Flag to stop docker
  set_fact:
    force_stop_docker_demon: "{{ not kubelet_systemd_unit_need_docker.changed | bool }}"
